# Generated by Django 2.2.1 on 2019-06-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190604_1953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together={('name', 'email')},
        ),
    ]
